# Generated by Django 3.1.3 on 2020-11-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rareuser',
            name='profile_image_url',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
